 USE FoodDelivery_DB;
 
 -- 1. List all pending orders with customer and restaurant details
SELECT o.order_id, c.name AS customer, r.name AS restaurant, o.status
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.status = 'pending';

-- 2. Total revenue generated by each restaurant
SELECT r.name AS restaurant, SUM(p.amount) AS total_revenue
FROM Payments p
JOIN Orders o ON p.order_id = o.order_id
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
WHERE p.status = 'successful'
GROUP BY r.name;

-- 3. Top 3 most expensive menu items
SELECT item_name, price FROM Menu_Items
ORDER BY price DESC
LIMIT 3;

-- 4. Average delivery time per delivery partner
SELECT dp.name AS partner, AVG(d.delivery_time) AS avg_time
FROM Deliveries d
JOIN Delivery_Partners dp ON d.partner_id = dp.partner_id
GROUP BY dp.name;

-- 5. Number of orders per customer
SELECT c.name, COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.name;

-- 6. Find most ordered menu item
SELECT m.item_name, COUNT(oi.item_id) AS times_ordered
FROM Order_Items oi
JOIN Menu_Items m ON oi.item_id = m.item_id
GROUP BY oi.item_id
ORDER BY times_ordered DESC
LIMIT 1;

-- 7. Show pending payments
SELECT p.order_id, c.name AS customer, p.amount, p.method, p.status
FROM Payments p
JOIN Orders o ON p.order_id = o.order_id
JOIN Customers c ON o.customer_id = c.customer_id
WHERE p.status = 'pending';

-- 8. Total orders handled by each delivery partner
SELECT dp.name, COUNT(d.delivery_id) AS total_deliveries
FROM Deliveries d
JOIN Delivery_Partners dp ON d.partner_id = dp.partner_id
GROUP BY dp.name;

-- 9. Restaurants with average rating above 4.3
SELECT name, rating FROM Restaurants
WHERE rating > 4.3;

-- 10. Customer order and payment summary
SELECT c.name, COUNT(o.order_id) AS total_orders, SUM(p.amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Payments p ON o.order_id = p.order_id
GROUP BY c.name;
